nodeLinker: node-modules
npmPublishAccess: "public"
npmRegistryServer: "https://registry.npmjs.org"
yarnPath: .yarn/releases/yarn-3.2.1.cjs

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
