nodeLinker: node-modules
npmPublishAccess: "public"
npmRegistryServer: "https://registry.npmjs.org"
yarnPath: .yarn/releases/yarn-3.2.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
