name: Setup
description: 'Setup JS workflow, install dependencies and cache them'
author: 'chillios-dev'

runs:
  using: 'composite'
  steps:
    - uses: dtinth/setup-github-actions-caching-for-turbo@a0e976d970c2a94366a26984efcef3030e2c0115
    - name: Setup PNPM
      shell: bash
      run: |
        npm install -g pnpm

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install packages
      shell: bash
      run: pnpm install --frozen-lockfile
