name: 'Install and cache'
description: 'Setup JS workflow, install dependencies and cache them'
author: 'Chillios'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.6.3
        run_install: false

    - uses: dtinth/setup-github-actions-caching-for-turbo@v1
      with:
        # Set the prefix for the cache keys.
        cache-prefix: swapkit_

    - uses: actions/cache@v3
      id: pnpm-cache
      with:
        path: ${{ steps.pnpm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Use Node.js 18.16
      uses: actions/setup-node@v3
      with:
        node-version: 18.16

    - shell: bash
      name: Install packages
      run: pnpm install --frozen-lockfile
