name: 'Install and cache'
description: 'Setup JS workflow, install dependencies and cache them'
author: 'Chillios'

runs:
  using: 'composite'
  steps:
    - uses: dtinth/setup-github-actions-caching-for-turbo@v1

    - uses: pnpm/action-setup@v2
      with:
        version: 8.6.3
        run_install: false

    - name: Get pnpm cache directory
      id: pnpm-cache-dir
      shell: bash
      run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      id: pnpm-cache
      with:
        path: ${{ steps.pnpm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Use Node.js 20.9
      uses: actions/setup-node@v3
      with:
        node-version: 20.9

    - shell: bash
      name: Install packages
      run: pnpm install --frozen-lockfile
