name: Check Token List
env:
  NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-workflow

      - name: Generate new token list
        run: |
          cd packages/swapkit/tokens
          pnpm generate-tokens

      - name: Push Token List Changes
        uses: devops-infra/action-commit-push@73d3ffed46e0782df6f046d15049aae82569b389
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_timestamp: false
          commit_prefix: "[Token List Update]"
          commit_message: "Update Token List"
          force: true
          target_branch: bot/token-list-update


      - name: Publish Token List
        run: |
          pnpm changeset version --snapshot nightly
          cd packages/swapkit/tokens
          npm publish
