name: Run dry build & test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/**'
      - 'internal/**'
      - 'yarn.lock'

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_run:
    if: contains(github.event.pull_request.title, ':tada:') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-workflow

      - name: Build and check size
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: ci
          skip_step: install
